name: ScrumBooster
description: Scrum Tutorial by PPLD1

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scoped_model:
  flutter_launcher_icons: ^0.6.1
  font_awesome_flutter: ^8.0.1
  dio: ^1.0.0
  cookie_jar: ^0.0.4
  flutter_svg:
  client_cookie:
  transparent_image: ^0.1.0
  path_provider: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_test_utils: ^1.0.0

flutter_icons:
  image_path: "assets/logos/logo-color.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/logo-color.png
    - assets/logos/logo-white.png
    - assets/logos/Makara-UI.png
    - assets/listGlossary/glossary.png
    - assets/listProblems/problems.png
    - assets/listCeremonies/ceremonies.png
    - assets/logos/logo-color.png
    - assets/logos/logo-white.png
    - assets/homepage/Product_Backlog.png
    - assets/homepage/Sprint_Evaluation.png
    - assets/homepage/Sprint_Exe.png
    - assets/homepage/Sprint_Planning.png
    - assets/scrumPhase/content_a.png
    - assets/scrumPhase/content_b.png
    - assets/scrumPhase/content_c.png
    - assets/scrumPhase/content_d.png
    - assets/scrumPhase/content_e.png
    - assets/scrumPhase/problem_a.png
    - assets/scrumPhase/problem_b.png
    - assets/scrumPhase/problem_c.png
    - assets/scrumPhase/problem_d.png
    - assets/scrumPhase/problem_e.png
    - assets/scrumPhase/problem_f.png
    - assets/scrum-board.png
    - assets/scrum-board-cloud.png

  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Black.ttf
    - asset: assets/fonts/Montserrat-BlackItalic.ttf
    - asset: assets/fonts/Montserrat-Bold.ttf
    - asset: assets/fonts/Montserrat-BoldItalic.ttf
    - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
    - asset: assets/fonts/Montserrat-ExtraLight.ttf
    - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
    - asset: assets/fonts/Montserrat-Italic.ttf
    - asset: assets/fonts/Montserrat-Light.ttf
    - asset: assets/fonts/Montserrat-LightItalic.ttf
    - asset: assets/fonts/Montserrat-Medium.ttf
    - asset: assets/fonts/Montserrat-MediumItalic.ttf
    - asset: assets/fonts/Montserrat-Regular.ttf
    - asset: assets/fonts/Montserrat-SemiBold.ttf
    - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
    - asset: assets/fonts/Montserrat-Thin.ttf
    - asset: assets/fonts/Montserrat-ThinItalic.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
