# Generated by Django 2.1.1 on 2019-02-25 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2047)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CMMIPractices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2047)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2047)),
                ('image', models.ImageField(upload_to='')),
                ('ceremonies_that_contain', models.ManyToManyField(to='rest_api.Ceremony')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2047)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2047)),
                ('image', models.ImageField(upload_to='')),
                ('can_be_solved_by_using', models.ManyToManyField(to='rest_api.CMMIPractices')),
                ('may_be_happen_at', models.ManyToManyField(to='rest_api.Ceremony')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2047)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer_key', models.IntegerField()),
                ('question_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Phase')),
            ],
        ),
        migrations.AddField(
            model_name='glossary',
            name='problem_that_contain',
            field=models.ManyToManyField(to='rest_api.Problem'),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='can_be_enchanched_by_using',
            field=models.ManyToManyField(to='rest_api.CMMIPractices'),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Phase'),
        ),
    ]
