# Generated by Django 2.1.1 on 2019-04-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processarea',
            old_name='ceremony',
            new_name='related_ceremony',
        ),
    ]
