# Generated by Django 2.1.1 on 2019-03-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2047)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('purpose_statement', models.CharField(max_length=2047)),
                ('introductory_notes', models.CharField(max_length=2047)),
                ('related_process_areas', models.ManyToManyField(related_name='_processarea_related_process_areas_+', to='rest_api.ProcessArea')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='to_satisfy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.ProcessArea'),
        ),
        migrations.AddField(
            model_name='cmmipractices',
            name='to_achieve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Goal'),
        ),
    ]
