# Generated by Django 2.1.1 on 2019-04-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20190423_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossary',
            old_name='name',
            new_name='title',
        ),
    ]
