# Generated by Django 2.0.6 on 2019-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20190304_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processarea',
            name='related_process_areas',
            field=models.ManyToManyField(blank=True, related_name='_processarea_related_process_areas_+', to='rest_api.ProcessArea'),
        ),
    ]
