# Generated by Django 2.1.1 on 2019-04-16 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20190416_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='can_be_solved_by_using',
        ),
    ]
