# Generated by Django 2.1.1 on 2019-04-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20190326_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremony',
            name='can_be_enchanched_by_using',
            field=models.ManyToManyField(blank=True, to='rest_api.CMMIPractices'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='ceremonies_that_contain',
            field=models.ManyToManyField(blank=True, to='rest_api.Ceremony'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='problem_that_contain',
            field=models.ManyToManyField(blank=True, to='rest_api.Problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='can_be_solved_by_using',
            field=models.ManyToManyField(blank=True, to='rest_api.CMMIPractices'),
        ),
    ]
