# Generated by Django 2.1.1 on 2019-04-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20190405_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremony',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cmmipractices',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='cmmipractices',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='phase',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='processarea',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
